# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

variables: 
  ## Add this under variables section in the pipeline
  azureSubscription: 'azure pay-as-you-go service connection'
  appName: 'weydz-node-docker'
  containerRegistry: 'index.docker.io'
  dockerRegistryServiceConnection: '4fa4efbc-59af-4c0b-8637-1d5bf7f268fc'
  imageRepository: 'weydenherrera/sample-node'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: 'latest'

pool:
  name: Default
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    docker buildx build --platform linux/arm64/v8,linux/amd64 -t weydenherrera/sample-node:latest .
    docker push weydenherrera/sample-node:latest
  displayName: 'npm install and build'

- task: AzureWebAppContainer@1
  displayName: 'Azure Web App on Container Deploy'
  inputs:
      azureSubscription: $(azureSubscription)
      appName: $(appName)
      containers: $(containerRegistry)/$(imageRepository):$(tag)
