# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

variables: 
  ## Add this under variables section in the pipeline
  azureSubscription: 'azure pay-as-you-go service connection'
  appName: 'weydz-node-docker'
  containerRegistry: 'index.docker.io'
  dockerRegistryServiceConnection: '4fa4efbc-59af-4c0b-8637-1d5bf7f268fc'
  imageRepository: 'weydenherrera/sample-node'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

pool:
  name: Default
  vmImage: ubuntu-latest

  stages:
  - stage: build
    displayName: Build
    jobs:
      - job: install node
        displayName: Install Nodejs
        steps:
          - task: NodeTool@0
            displayName: 'Install Node.js'
            inputs:
              versionSpec: '20.x'
          - script: |
              npm install
              docker buildx build --platform linux/arm64/v8,linux/amd64 -t weydenherrera/sample-node:$(tag) .
              docker push weydenherrera/sample-node:$(tag)
            displayName: 'npm install and build'
  - stage: deploy
    displayName: Deploy
    dependsOn: build
    jobs:
      - job: deploy to app service
        displayName: Deploy to App Service
        steps:
          - task: AzureWebAppContainer@1
            displayName: 'Azure Web App on Container Deploy'
            inputs:
              azureSubscription: $(azureSubscription)
              appName: $(appName)
              containers: $(containerRegistry)/$(imageRepository):$(tag)
